// Code generated by protoc-gen-go. DO NOT EDIT.
// source: banter.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	banter.proto

It has these top-level messages:
	Peer
	Response
	Message
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
)

var Status_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}
var Status_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Msg int32

const (
	Msg_PING Msg = 0
	Msg_PONG Msg = 1
)

var Msg_name = map[int32]string{
	0: "PING",
	1: "PONG",
}
var Msg_value = map[string]int32{
	"PING": 0,
	"PONG": 1,
}

func (x Msg) String() string {
	return proto.EnumName(Msg_name, int32(x))
}
func (Msg) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Peer struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	Port    string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Peer) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Peer) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type Response struct {
	Status Status  `protobuf:"varint,1,opt,name=status,enum=banter.Status" json:"status,omitempty"`
	Ttl    float32 `protobuf:"fixed32,2,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *Response) GetTtl() float32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type Message struct {
	Msg    Msg   `protobuf:"varint,1,opt,name=msg,enum=banter.Msg" json:"msg,omitempty"`
	Origin *Peer `protobuf:"bytes,2,opt,name=origin" json:"origin,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Message) GetMsg() Msg {
	if m != nil {
		return m.Msg
	}
	return Msg_PING
}

func (m *Message) GetOrigin() *Peer {
	if m != nil {
		return m.Origin
	}
	return nil
}

func init() {
	proto.RegisterType((*Peer)(nil), "banter.Peer")
	proto.RegisterType((*Response)(nil), "banter.Response")
	proto.RegisterType((*Message)(nil), "banter.Message")
	proto.RegisterEnum("banter.Status", Status_name, Status_value)
	proto.RegisterEnum("banter.Msg", Msg_name, Msg_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Banter service

type BanterClient interface {
	Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error)
}

type banterClient struct {
	cc *grpc.ClientConn
}

func NewBanterClient(cc *grpc.ClientConn) BanterClient {
	return &banterClient{cc}
}

func (c *banterClient) Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/banter.banter/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Banter service

type BanterServer interface {
	Send(context.Context, *Message) (*Response, error)
}

func RegisterBanterServer(s *grpc.Server, srv BanterServer) {
	s.RegisterService(&_Banter_serviceDesc, srv)
}

func _Banter_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BanterServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/banter.banter/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BanterServer).Send(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Banter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "banter.banter",
	HandlerType: (*BanterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Banter_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "banter.proto",
}

func init() { proto.RegisterFile("banter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x6d, 0x3e, 0xdc, 0xb6, 0xd3, 0x52, 0x97, 0x39, 0x45, 0x45, 0x90, 0x20, 0xa2, 0x3d, 0xf4,
	0x90, 0xfe, 0x03, 0x51, 0xaa, 0x48, 0x92, 0xb2, 0xbd, 0x79, 0x4b, 0xc8, 0x10, 0x0a, 0x36, 0x09,
	0x3b, 0xeb, 0xff, 0x97, 0x6c, 0x76, 0xbd, 0xbd, 0x79, 0xf3, 0xe6, 0xcd, 0xcc, 0x83, 0x75, 0x5d,
	0x75, 0x86, 0xf4, 0x6e, 0xd0, 0xbd, 0xe9, 0x51, 0x4c, 0x55, 0xfa, 0x01, 0xf1, 0x91, 0x48, 0x23,
	0x42, 0xdc, 0x55, 0x17, 0x4a, 0x82, 0x87, 0xe0, 0x79, 0xa9, 0x2c, 0xc6, 0x04, 0xe6, 0x55, 0xd3,
	0x68, 0x62, 0x4e, 0x42, 0x4b, 0xfb, 0x72, 0x54, 0x0f, 0xbd, 0x36, 0x49, 0x34, 0xa9, 0x47, 0x9c,
	0xbe, 0xc1, 0x42, 0x11, 0x0f, 0x7d, 0xc7, 0x84, 0x4f, 0x20, 0xd8, 0x54, 0xe6, 0x97, 0xad, 0xdf,
	0x26, 0xdb, 0xec, 0xdc, 0xf2, 0x93, 0x65, 0x95, 0xeb, 0xa2, 0x84, 0xc8, 0x98, 0x1f, 0xeb, 0x1e,
	0xaa, 0x11, 0xa6, 0x05, 0xcc, 0x73, 0x62, 0xae, 0x5a, 0xc2, 0x7b, 0x88, 0x2e, 0xdc, 0x3a, 0x87,
	0x95, 0x77, 0xc8, 0xb9, 0x55, 0x23, 0x8f, 0x8f, 0x20, 0x7a, 0x7d, 0x6e, 0xcf, 0x9d, 0x1d, 0x5f,
	0x65, 0x6b, 0xaf, 0x18, 0xff, 0x51, 0xae, 0xb7, 0xbd, 0x03, 0x31, 0xed, 0x44, 0x01, 0x61, 0xf9,
	0x25, 0x67, 0xb8, 0x84, 0xab, 0x77, 0xa5, 0x4a, 0x25, 0x83, 0xed, 0x0d, 0x44, 0x39, 0xb7, 0xb8,
	0x80, 0xf8, 0xf8, 0x59, 0x1c, 0xe4, 0xcc, 0xa2, 0xb2, 0x38, 0xc8, 0x20, 0xdb, 0x83, 0x4b, 0x08,
	0x5f, 0x20, 0x3e, 0x51, 0xd7, 0xe0, 0xf5, 0xff, 0x05, 0xd3, 0x7d, 0xb7, 0xd2, 0x13, 0xfe, 0xed,
	0xd7, 0xf8, 0x3b, 0x1c, 0xea, 0x5a, 0xd8, 0x84, 0xf7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13,
	0x98, 0xc0, 0xc1, 0x71, 0x01, 0x00, 0x00,
}
